[package]
name = "gen-readme"
version = "0.1.1"
edition = "2021"
description = "Just a simple readme generator that uses a static template."
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
